#SIZES
SCREEN_HEIGHT = 800
SCREEN_WIDTH = 1400
LINE_WIDTH = 5
BOARD_DIMENSIONS = 4
BOARD_ROWS = 4
BOARD_COLS = 4
SQUARE_WIDTH = SCREEN_WIDTH // 16
SQUARE_HEIGHT = SCREEN_HEIGHT // 4
SQUARE_SIZE = 87
DIMENSION_SIZE = SQUARE_WIDTH * 4
CIRCLE_RADIUS = SQUARE_WIDTH // 4
CIRCLE_WIDTH = 5
CROSS_WIDTH = 10


# Colors
BG_COLOR = (20, 20, 20)
LAYER_COLOR = (50, 50, 50)
LAYER_COLOR_SELECTED = (200, 200, 200)
CELL_COLOR = (90, 90, 90)
CELL_BORDER = (255, 255, 255)
CIRCLE_COLOR = (255, 0, 0)
CROSS_COLOR = (0, 200, 0)

# Cube
CUBE_SIZE = 400
LAYER_COUNT = 4
CELLS_PER_LAYER = 4
CELL_SIZE = CUBE_SIZE / CELLS_PER_LAYER
LAYER_SPACING = CUBE_SIZE / LAYER_COUNT

# Rotation
rotation_x, rotation_y = 0.3, 0.5
is_dragging = False
last_mouse_pos = None

# Layer & cells
current_layer = 1
hovered_cell = None
clicked_cells = set()

#SETTINGS
PLAYER = 1
AI = 2
maxDepth = 1